# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7a5d3042f501c137b9d5f64684280eb655b448ce73479b77f9da9fb4b637a8377d4c6d63917422b708dbeff85bd31da7672c79a535350f31ba788508a7ca7352

test:
  secret_key_base: a1b8ca49d7fa96501060e887a10434ab8fe9e222e869f29a4f1a6e9a707cfb48e14a82a1a955fa138f1f78c88d2ea8bf19f1d76a244eb5d99b401049af52ecca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
